### ISSUE TITLE
EDA

### ISSUE THREAD

**Issue by alepinb** [AI-School-F5-P3/airbnb_grupo1#1]
Debemos extraer toda la información útil que seamos capaces de encontrar en los datasets cedidos por Airbnb.
Cuantas más info encontremos, mejor (explicaciones a outliers, confirmación de hipótesis, patrones extraños, etc).

Análisis exploratorio de datos (EDA) completo con visualizaciones clave que
muestren la distribución de las variables, patrones generales, detección de outliers,
etc.

**Comment by aitorph7** [comment]
Me ha chivado "un pajarito" que la librería `dataprep` es de gran ayuda a la hora de comenzar a trabajar con los conjuntos de datos con mucho terreno ya avanzado de antemano, porque realiza un primer EDA bastante completo con el cual puedes comenzar a crear hipótesis e interpretaciones.

[dataprep.ai](https://dataprep.ai/)

el comando `dataprep.eda` es el comienzo.
