### ISSUE TITLE
Uso de visualizaciones avanzadas

### ISSUE THREAD

**Issue by alepinb** [AI-School-F5-P3/airbnb_grupo1#6]
Uso de librerías específicas para visualizar y comprender los conjuntos de datos, como Plotly, Seaborn o alguna librería que permita la representación de los datos sobre mapas... incluyendo gráficos interactivos.

**Comment by aitorph7** [comment]
Ls librería `folium` puede ser de ayuda para representar los datos sobre mapas geográficos de las ciudades en las qu estamos trabajando.
